// Command third-party-notices generates the license bundle shipped with the
// Brclio Mail production binary.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const productionPackage = "./cmd/brclio-mail"

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
	Replace *module
}

type listedPackage struct {
	Standard bool
	Module   *module
}

type component struct {
	Name  string
	Files []noticeFile
}

type noticeFile struct {
	Name    string
	Content string
}

func main() {
	output := flag.String("output", "THIRD_PARTY_NOTICES", "path to the generated notice bundle")
	check := flag.Bool("check", false, "verify the output is current instead of writing it")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected positional arguments: %s", strings.Join(flag.Args(), " "))
	}

	generated, err := generate()
	if err != nil {
		fatalf("generate notices: %v", err)
	}
	if *check {
		committed, err := os.ReadFile(*output)
		if err != nil {
			fatalf("read %s: %v", *output, err)
		}
		if !bytes.Equal(committed, generated) {
			fatalf("%s is out of date; run make third-party-notices", *output)
		}
		fmt.Printf("%s is up to date\n", *output)
		return
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatalf("write %s: %v", *output, err)
	}
	fmt.Printf("wrote %s\n", *output)
}

func generate() ([]byte, error) {
	components, err := productionComponents()
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	output.WriteString("BRCLIO MAIL THIRD-PARTY SOFTWARE NOTICES\n\n")
	output.WriteString("This file is generated by `make third-party-notices`; do not edit it by hand.\n")
	output.WriteString("It covers the Go runtime and standard library plus every non-project Go module\n")
	output.WriteString("reachable from ./cmd/brclio-mail for the canonical CGO-disabled Linux/amd64 release.\n")
	output.WriteString("Project-owned and Esther-derived files are licensed separately; see LICENSE,\n")
	output.WriteString("NOTICE, and LICENSES/.\n\n")
	output.WriteString("Components:\n")
	for _, item := range components {
		fmt.Fprintf(&output, "- %s\n", item.Name)
	}
	for _, item := range components {
		output.WriteString("\n================================================================================\n")
		output.WriteString(item.Name)
		output.WriteString("\n================================================================================\n")
		for _, file := range item.Files {
			fmt.Fprintf(&output, "\n--- %s ---\n\n%s\n", file.Name, file.Content)
		}
	}
	return []byte(output.String()), nil
}

func productionComponents() ([]component, error) {
	standardFiles, err := noticeFiles(runtime.GOROOT())
	if err != nil {
		return nil, fmt.Errorf("Go toolchain notices: %w", err)
	}
	components := []component{{Name: "Go runtime and standard library " + runtime.Version(), Files: standardFiles}}

	goCommand := filepath.Join(runtime.GOROOT(), "bin", "go")
	command := exec.Command(goCommand, "list", "-deps", "-json", productionPackage)
	command.Env = environmentWith(os.Environ(), map[string]string{
		"CGO_ENABLED":  "0",
		"GOARCH":       "amd64",
		"GOEXPERIMENT": "",
		"GOFLAGS":      "",
		"GOOS":         "linux",
		"GOPROXY":      "off",
		"GOTOOLCHAIN":  "local",
		"GOWORK":       "off",
	})
	stdout, err := command.StdoutPipe()
	if err != nil {
		return nil, err
	}
	var stderr bytes.Buffer
	command.Stderr = &stderr
	if err := command.Start(); err != nil {
		return nil, err
	}

	modules := make(map[string]module)
	var dependencyErr error
	decoder := json.NewDecoder(stdout)
	for {
		var pkg listedPackage
		if err := decoder.Decode(&pkg); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			_ = command.Process.Kill()
			_ = command.Wait()
			return nil, fmt.Errorf("decode go list output: %w", err)
		}
		if pkg.Standard || pkg.Module == nil || pkg.Module.Main {
			continue
		}
		resolved := *pkg.Module
		name := resolved.Path + " " + resolved.Version
		if resolved.Replace != nil {
			replacement := *resolved.Replace
			if replacement.Version == "" {
				if dependencyErr == nil {
					dependencyErr = fmt.Errorf("dependency %s uses an unpinned local replacement %s", resolved.Path, replacement.Path)
				}
				continue
			}
			name += " => " + replacement.Path + " " + replacement.Version
			resolved.Dir = replacement.Dir
		}
		if resolved.Version == "" || resolved.Dir == "" {
			if dependencyErr == nil {
				dependencyErr = fmt.Errorf("dependency %s does not have a pinned version and module directory", resolved.Path)
			}
			continue
		}
		modules[name] = module{Path: name, Dir: resolved.Dir}
	}
	if err := command.Wait(); err != nil {
		return nil, fmt.Errorf("go list failed: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	if dependencyErr != nil {
		return nil, dependencyErr
	}

	names := make([]string, 0, len(modules))
	for name := range modules {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		files, err := noticeFiles(modules[name].Dir)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		components = append(components, component{Name: name, Files: files})
	}
	return components, nil
}

func environmentWith(environment []string, overrides map[string]string) []string {
	keys := make([]string, 0, len(overrides))
	for key := range overrides {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	result := make([]string, 0, len(environment)+len(overrides))
	for _, entry := range environment {
		keep := true
		for _, key := range keys {
			if strings.HasPrefix(entry, key+"=") {
				keep = false
				break
			}
		}
		if keep {
			result = append(result, entry)
		}
	}
	for _, key := range keys {
		result = append(result, key+"="+overrides[key])
	}
	return result
}

func noticeFiles(directory string) ([]noticeFile, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, entry := range entries {
		if !entry.Type().IsRegular() || !isNoticeName(entry.Name()) {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	if len(names) == 0 {
		return nil, fmt.Errorf("no root LICENSE, COPYING, NOTICE, PATENTS, or COPYRIGHT file found in %s", directory)
	}

	files := make([]noticeFile, 0, len(names))
	for _, name := range names {
		content, err := os.ReadFile(filepath.Join(directory, name))
		if err != nil {
			return nil, err
		}
		text := strings.ReplaceAll(string(content), "\r\n", "\n")
		text = strings.TrimRight(text, "\n")
		files = append(files, noticeFile{Name: name, Content: text})
	}
	return files, nil
}

func isNoticeName(name string) bool {
	upper := strings.ToUpper(name)
	for _, root := range []string{"LICENSE", "COPYING", "NOTICE", "PATENTS", "COPYRIGHT"} {
		if upper == root || strings.HasPrefix(upper, root+".") || strings.HasPrefix(upper, root+"-") || strings.HasPrefix(upper, root+"_") {
			return true
		}
	}
	return false
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "third-party-notices: "+format+"\n", arguments...)
	os.Exit(1)
}
